// Generated by CoffeeScript 1.6.2
var SpreadsheetServer;

SpreadsheetServer = require('./spreadsheetserver');

if (process.argv.length !== 3) {
  console.log('Command line argument should be port number');
  return;
}

new SpreadsheetServer(process.argv[2]);
