// Generated by CoffeeScript 1.6.2
var SpreadsheetServer, spreadsheetServer;

SpreadsheetServer = require('./spreadsheetserver.js');

if (process.argv.length !== 3) {
  console.log('Command line argument should be port number');
  return;
}

spreadsheetServer = new SpreadsheetServer(process.argv[2]);
